### ISSUE TITLE
loadCardForm

### ISSUE THREAD

**Issue by jgmandujano** [open-pay/openpay-swift-ios#1]
Tengo un proyecto donde intento integrar la librería, todo parece ir bien pero el formulario no se muestra, tampoco muestra algún error informando que algo esté mal.

**Comment by igrijalva** [comment]
Que tal,

Podrías compartirnos por favor los detalles sobre: versión de swift, versión de xcode, llamado a la librería.

Te pido también que por favor te asegures de ligar la librería de Openpay en la configuración del proyecto:
![linklibrary](https://cloud.githubusercontent.com/assets/23488784/21505021/2ee09f96-cc29-11e6-9f15-17c7294f0c31.png)

**Comment by jgmandujano** [comment]
Hola.
El problema es con los UITableViewController, si se us un UIViewController se comporta de manera normal.

Al parecer esto es debido a que el formulario se agrega al UIViewController actual y no a través de un segue.

**Comment by igrijalva** [comment]
Ok realizaré algunas pruebas y haré los ajustes necesarios.

Gracias!

**Comment by igrijalva** [comment]
Se realizaron los ajustes y funciona correctamente otros ViewController
