### ISSUE TITLE
dyld: Library not loaded: @rpath/Openpay.framework/Openpay   Referenced from: /var/containers/Bundle/Application/BC9F1779-AD36-4B21-898B-93FF8A247F41/BBB.app/BBB   Reason: image not found in device xcode 9.2,iOS-10.13.3

### ISSUE THREAD

**Issue by HaneetGH** [open-pay/openpay-swift-ios#10]

**Comment by fantasma10** [comment]
Alguna solución para dicho problema ?

**Comment by igrijalva** [comment]
En la pestaña "General"  de TARGETS, hay dos secciones "Embedded Binaries" y "Linked Frameworks and Libraries", asegúrate de agregar la librería  de Openpay en ambos.

![image](https://user-images.githubusercontent.com/23488784/47512458-e1f1e380-d841-11e8-898d-8d7ac3c2b2bf.png)
