### ISSUE TITLE
Cant' open a compile with xCode 7.3.1

### ISSUE THREAD

**Issue by RV2013** [open-pay/openpay-swift-ios#11]
I am trying to integrate Openpay.xcodeproj file in my current workspace on xcode 7.3.1 but it says couldn't open file 
es : Estoy tratando de integrar el archivo Openpay.xcodeproj en mi espacio de trabajo actual en xcode 7.3.1 pero dice que no se pudo abrir el archivo

**Comment by igrijalva** [comment]
Que tal @RV2013 realicé una prueba con XCode 7.3.1 y me permitió cargar el proyecto, me podrías compartir mayor detalle de cómo estas tratando de integrar el framework por favor.

![image](https://user-images.githubusercontent.com/23488784/37929534-7eb817e4-30fd-11e8-81e8-bf3044ed5649.png)

De cualquier forma yo te recomendaría actualizar el XCode a la versión mas reciente ya que estamos trabajando en mejoras y las siguientes actualizaciones requerirán Swift 3.0


Saludos.
