### ISSUE TITLE
Incompatible versions of Swift

### ISSUE THREAD

**Issue by eitanaviv** [open-pay/openpay-swift-ios#15]
Could you please recompile this library using the latest Swift and Xcode?
I'm using Xcode 9.4 (latest - 9F1027a) and Swift 4.1 and cannot use this library with my project.

**Comment by Dimakersmx** [comment]
No funciona el formulario para agregar tarjetas en concreto el boton de cancelar , el pickerView para la fecha de expiración no abre, por lo que no puedo continuar con la integración
