### ISSUE TITLE
Actualicen la documentacion

### ISSUE THREAD

**Issue by glassipbel** [open-pay/openpay-swift-ios#16]
Tengo realmente varias criticas.
La primera, dice que debo descargar un SDK 2.0 supuestamente zip y que es un framework, lo cual no existe en ningun lado de esta pagina.
Si descargo las clases de como fue armado, realmente hay muchas cosas que tienen unwraps no seguros...
La distribucion al ser de esta manera, si hay una actualizacion es un dolor de cabeza... Tendrian que utilizar Cocoapods no les tardaria mas de 30 minutos migrarlo...
Hay varios metodos que se utilizan que ya quedaron deprecados en swift 4, esos tienen que actualizarlos.
En concreto, tienen alguna documentacion actualizada para seguir? no entiendo como puede ser tan poco serio un SDK de una empresa que esta buscando crecer.
Gracias.

**Comment by glassipbel** [comment]
Por cierto, tambien hay memory leaks debido a malas practicas de como guardar callbacks.. entre otras cosas.

**Comment by calahe** [comment]
Hola Kevin

Agradezco tus comentarios. Tienes algún  correo y/o teléfono para poder
contactarte.

Saludos

**Comment by glassipbel** [comment]
Hola si, mi correo es kevin.belter@outlook.com y mi telefono es +5215566317188
