### ISSUE TITLE
how to create a card token for 'n' number of transection 

### ISSUE THREAD

**Issue by harshilkotecha** [open-pay/openpay-swift-ios#18]
here openpay can support for any number transaction using saved card .? like stripe and other payment getaway ?

**Comment by igrijalva** [comment]
Hello Harshil,

Of course, you can save a card and reuse it, please check the following
link: https://www.openpay.mx/en/docs/save-card.html



<http://www.openpay.mx>   *Israel Grijalva  | Desarrollo*
blog.openpay.mx
@OpenpayMX <https://twitter.com/OpenpayMX>   Teléfono: +52
<%2B52%20%2855%29%204170.3567%20ext.1507>*(55) 4163 4898*
Email: israel.grijalva@openpay.mx
<http://www.openpay.mx>

**Comment by harshilkotecha** [comment]
Thank you @igrijalva
