### ISSUE TITLE
KDataCollector Collector timed out: Web Collector

### ISSUE THREAD

**Issue by victorgilalejandria** [open-pay/openpay-swift-ios#2]
Buenas, estoy tratando de implementar el método createDeviceSessionId pero siempre que ejecuta el KDataCollector, me devuelve ese error. Mas específicamente `[Client] Failure to deallocate CLLocationManager on the same runloop as its creation may result in a crash` 

Esta es la función relevante al problema: 

`    func setupOpenpay() {
        self.openpayObject = Openpay()
        self.openpayObject.createDeviceSessionId(successFunction: { (sessionID) in
            self.sessionID = sessionID
        }) { _ in }
    }
`

Incluso aumenté el tiempo del timeout mediante ` KDataCollector.shared().timeoutInMS = 300000` pero sigue dándome el mismo error.

**Comment by igrijalva** [comment]
Que tal, puedes intentar nuevamente por favor.

**Comment by victorgilalejandria** [comment]
Sigue igual.

**Comment by victorgilalejandria** [comment]
Aparentemente no puedo hacer las dos llamadas juntas, coloque una al momento de iniciar la vista y la siguiente instrucción justo antes de levantar la ventana de cobro y funcionó.

**Comment by igrijalva** [comment]
Es correcto, primero se debe inicializar la librería y posteriormente generar el DeviceSessionId
