### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler

### ISSUE THREAD

**Issue by AlexandroRM** [open-pay/openpay-swift-ios#23]
your library doesn't work in Xcode 10 with swift 4.2

**Comment by harifsp** [comment]
unable to create instance for openpay
![screenshot 2018-11-08 at 6 57 51 pm](https://user-images.githubusercontent.com/30861420/48201623-b5cd7b00-e388-11e8-8dac-11468a9eb2d1.png)

**Comment by uresti404** [comment]
> unable to create instance for openpay
> ![screenshot 2018-11-08 at 6 57 51 pm](https://user-images.githubusercontent.com/30861420/48201623-b5cd7b00-e388-11e8-8dac-11468a9eb2d1.png)

¿Did you solve it?  I have the same issue.

**Comment by moyses8a** [comment]
Yes, I found the files that I needed here -> [https://github.com/open-pay/openpay-swift-ios/tree/master/v2/Openpay/Openpay](https://github.com/open-pay/openpay-swift-ios/tree/master/v2/Openpay/Openpay), just copy them to your project, and that's it.
**I fix link** @Gralucenas, thanks

**Comment by Gralucenas** [comment]
@moyses8a link is broken :(

**Comment by GerardoPM** [comment]
> Yes, I found the files that I needed here -> https://github.com/open-pay/openpay-swift-ios/tree/master/v2/Openpay/Openpay, just copy them to your project, and that's it.
> **I fix link** @Gralucenas, thanks

Where did you copy the files?

**Comment by moyses8a** [comment]
> > Yes, I found the files that I needed here -> https://github.com/open-pay/openpay-swift-ios/tree/master/v2/Openpay/Openpay, just copy them to your project, and that's it.
> > **I fix link** @Gralucenas, thanks
> 
> Where did you copy the files?

Choose your best option in the structure of your project. In my case I put it in a folder called OpenPay in the root directory.
And then 'import Openpay' would be available wherever you need it.

**Comment by astaeduardomartinez** [comment]
@AlexandroRM Just delete OpenPay.framework and reimport it, clean project and rebuild

**Comment by hugohernandez** [comment]
Hi, we just uploaded v2.0.4 SDK that includes support for Swift 5.
