### ISSUE TITLE
can't get CVV

### ISSUE THREAD

**Issue by nirav-kotecha** [open-pay/openpay-swift-ios#24]
i am fetching all card details and i am getting all card details like number, expMonth, expYear and all but i can't get CVV. its returning blank ("").

card is OPToken Object
i am getting as a ==> card.card.cvv2
while card.card.number and others are working.

**Comment by nirav-kotecha** [comment]
```
private func sendFunction( method: String,
                       data: Dictionary<String, Any>!,
                       httpMethod: String,
                       successFunction: @escaping (_ responseParams: OPToken) -> Void,
                       failureFunction: @escaping (_ error: NSError) -> Void)
```

in above function i am passing data like following:
`Optional(["expiration_year": "xx", "card_number": "xxxxxxxxxxxx", "holder_name": "xxxxxxxx", "cvv2": "123", "expiration_month": "xx"])`
in data, cvv is passing.

when we received response of create token at that time not receiving CVV.
response like this way..
["id": xxxxxxxxx, "card": {
    address = "xxxxxx";
    brand = xxxx;
    "card_number" = xxxxxxxx;
    "creation_date" = "xxxxx";
    "expiration_month" = xxxx;
    "expiration_year" = xxxx;
    "holder_name" = "xxxxxxxxxxxxxx";
}]
NO CVV

**Comment by igrijalva** [comment]
Hi,

When a stored card is queried, due to security policies, the card number is masked and the cvv is not included in the response
