### ISSUE TITLE
Lanza un error en el loadCardForm

### ISSUE THREAD

**Issue by aniiskywalker** [open-pay/openpay-swift-ios#28]
Estoy tratando de utilizar el loadCardForm pero me regresa un error y truena (todo lo demás funciona perfecto):
Lenguaje: Swift v. 4.0
CÓDIGO:
```
var openpay: Openpay!

openpay = Openpay(withMerchantId: MERCHANT_ID, andApiKey: API_KEY, isProductionMode: false, isDebug: false)
        openpay.createDeviceSessionId(successFunction: successSessionID, failureFunction: failSessionID)


openpay.loadCardForm(in: self, successFunction: successCard, failureFunction: failCard, formTitle: "Openpay")
```
![Captura de pantalla 2019-03-26 a la(s) 15 22 52](https://user-images.githubusercontent.com/37088363/55034502-2fce6b80-4fdb-11e9-9807-0c17bb767988.png)
UPDATE: 
Cree otro proyecto para probar el framework e hize exactamente lo mismo que con mi proyecto al que quiero integrar openpay y funciona bien, no sé si se deba a que estoy usando navigation, no sé si sea por los pods que estoy utilizando pero sigue tronando.

**Comment by aniiskywalker** [comment]
Se solucionó

**Comment by moises503** [comment]
Cual fue tu solución ?

**Comment by aniiskywalker** [comment]
Estaba relacionada a localization strings, yo tengo español y tenia español Latinoamérica, ahí tronaba, debía cambiar español Latinoamérica por español de México

**Comment by moises503** [comment]
Ok voy a verificar, llevo 1 semana tratando de implementar. Gracias !

**Comment by aniiskywalker** [comment]
De acuerdo! Me comentas si te sirvió de algo :) @moises503

**Comment by moises503** [comment]
@aniiskywalker listo ya lanza el formulario, pero ahora me manda otro error: 
![Captura de Pantalla 2019-05-29 a la(s) 11 35 23](https://user-images.githubusercontent.com/22843235/58574576-e3cfbb00-8205-11e9-88bf-3ba343af04cb.png)
Esta asociado al AppDelegate especificamente en:
**Openpay`@objc Openpay.Openpay.(keyboardWillBeHidden in _156CF1A2C97B94A39272735542C02521)(notification: __C.NSNotification) -> ():**
Ocurre cuando intentas escribir o cambiar a otro campo del formulario.

**Comment by aniiskywalker** [comment]
@moises503 estas mandando a una siguiente pantalla o sobre la misma? Porque el error está relacionado a la manera en la que el formulario de openpay está construido.. creo.. porque a mi lo que me pasó es que, al ir a una siguiente pantalla y teniendo un formulario en ella tronaba pero sobre una librería que se llama IQKeyboardManager, lo que hice fue que destruí la variable openpay que había declarado, solo al hacer una acción de transición de pantalla (no en el willDisappear), espero que sea tu caso

**Comment by moises503** [comment]
Lo que hago es que tengo un tableview con la lista de tarjetas agregadas previamente por el usuario, en la parte inferior tengo un botón para agregar un nueva tarjeta, cuando presiona el botón le despliega el form de openpay.

**Comment by aniiskywalker** [comment]
@moises503 de acuerdo, entonces donde truena es sobre el mismo formulario de openpay?

**Comment by moises503** [comment]
@aniiskywalker si así es cuando lo muestro e intento interactuar colocando la info solicitada manda el error asociado al teclado. Ya sea que comience a escribir o me mueva a otro campo.

**Comment by aniiskywalker** [comment]
@moises503 No se me ocurre que pudiera ser, a mi me tronaba pero era en cuanto cambiaba de pantalla y esa pantalla tenía un input, por eso tenía que destruir la variable. No he visto errores relacionados a eso que me comentas. 
Disculpa que ya no te pude ayudar más, espero que lo resuelvas!

**Comment by moises503** [comment]
@aniiskywalker te agradezco tu apoyo !, la verdad me sirvió bastante, voy a seguir depurando esa parte, en cuanto tenga la solución la posteo por aquí. Saludos !

**Comment by aniiskywalker** [comment]
@moises503 no hay de que, mucha suerte!!. Saludos!
