### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by aosorio-avilez** [open-pay/openpay-swift-ios#29]
La librería no funciona con la nueva versión de Xcode 10.2 con Swift 4.2

![imagen](https://user-images.githubusercontent.com/11239855/55370263-1fc0fb00-54b7-11e9-9d44-3350c072aea6.png)

**Comment by fzunigad** [comment]
Estamos en las mismas, necesitamos actualizar a Xcode 10.2 pero esta librería nos retiene en Xcode 10.1.

**Comment by fzunigad** [comment]
Como "workaround" bajamos el proyecto desactualizado de este repositorio hecho en swift 3, lo pasamos a swift 4.2 y eso corre en Xcode 10.2. Estamos igual a la espera de una actualización del framework pero al menos podemos avanzar con lo mencionado anteriormente.

**Comment by joseangelrg30** [comment]
Alguna actualización de este problema?

**Comment by DanielTellez96** [comment]
Todavía no actualizan

**Comment by joseangelrg30** [comment]
> Como "workaround" bajamos el proyecto desactualizado de este repositorio hecho en swift 3, lo pasamos a swift 4.2 y eso corre en Xcode 10.2. Estamos igual a la espera de una actualización del framework pero al menos podemos avanzar con lo mencionado anteriormente.

fzunigad podrías compartir el compilado en swift 4.2 ? es que ya no tengo el Xcode 10.1

**Comment by aniiskywalker** [comment]
> Como "workaround" bajamos el proyecto desactualizado de este repositorio hecho en swift 3, lo pasamos a swift 4.2 y eso corre en Xcode 10.2. Estamos igual a la espera de una actualización del framework pero al menos podemos avanzar con lo mencionado anteriormente.

También me gustaría que me lo pudieras compartir porfa :)

**Comment by fzunigad** [comment]
Hola, les dejo el link para poder bajar Xcode 10.1 y asi poder hacer el workaround: https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_10.1/Xcode_10.1.xip. Ahora no estoy viendo ese proyecto por lo que no tengo acceso a esos archivos. Espero les ayude. Gracias 

Y como hacer el proceso esta aca:
> Yes, I found the files that I needed here -> https://github.com/open-pay/openpay-swift-ios/tree/master/v2/Openpay/Openpay, just copy them to your project, and that's it.

**Comment by aniiskywalker** [comment]
@fzunigad mil gracias, justo eso hice ayer, descargue el Xcode 10.1 y como mi código está en swift 4 no tuve ningún problema en volver a compilar y creo que hasta que no actualicen ahí nos vamos a quedar :/, ya no podré compilar en iPhones con iOS 12.2 hahaha, pero en fin. Te agradezco :)

**Comment by hugohernandez** [comment]
Hola, se acaba de subir la v2.0.4 del SDK que incluye compatibilidad con Swift 5.
