### ISSUE TITLE
Error al importar la libreria, versiones de swift incompatibles

### ISSUE THREAD

**Issue by aniiskywalker** [open-pay/openpay-swift-ios#31]
Hola, he integrado anteriormente la librería y funcionaba muy bien, pero en días posteriores actualicé mi versión de Xcode para poder compilar en la nueva versión de iOS, por lo que al querer compilar en esta me apareció el error:
`error: The following binaries use incompatible versions of Swift:
/Users/user/Library/Developer/Xcode/DerivedData/App-bynbdrqivtjxpbfuifksjmgqwiwj/Build/Products/Debug-iphoneos/App.app/App
/Users/user/App/Openpay.framework/Openpay` 
Versión de Xcode: `Version 10.2.1 (10E1001)`
Versión de Swift:` Swift 4`
Versión de OpenPay: `SDK-v2.0.3`

![Captura de Pantalla 2019-04-26 a la(s) 12 43 45](https://user-images.githubusercontent.com/37088363/56826186-29712080-6821-11e9-8d40-4b394e45f3d0.png)

**Comment by DanielReyesDev** [comment]
@aniiskywalker  al final lo pudiste importar en Swift? Tengo mis dudas de qué versión es la última si la de Objective-C o la de Swift 🤔

**Comment by aniiskywalker** [comment]
@DanielReyesDev hola Daniel, no, al final lo que hice fue descargar el Xcode 10.1 y compilar mi proyecto. Si te refieres a la versión de openpay, yo estoy usando la de swift, desconozco si la de objective-C esté actualizada. Saludos

**Comment by hugohernandez** [comment]
Hola a tod@s, se acaba de subir la v2.0.4 del SDK que incluye compatibilidad con Swift 5.
