### ISSUE TITLE
Unexpected found nil

### ISSUE THREAD

**Issue by risalgue** [open-pay/openpay-swift-ios#34]
Implemente la version 2.0.7 en el Xcode 10.2.1, trabaja perfectamente incluso el cardView con el manejo de los saltos de los texfield que antes daban problemas o se veían extraños. ahora al implementarlo en conjunto con el GMSAutocompleteViewController para el completamiento de las direcciones del Google Maps, este da error, y debe ser el mismo caso de las versiones anteriores donde se tiene un observer de notificación en la clase Openpay para el teclado: " NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillBeHidden(notification:)), name: UIResponder.keyboardWillHideNotification, object: nil)" la cual responde al la función:
@objc private func keyboardWillBeHidden(notification: NSNotification) {
        let contentInsets = UIEdgeInsets.zero
        self.scrollView.contentInset = contentInsets
        self.scrollView.scrollIndicatorInsets = contentInsets
    }
Y siempre que se haga un post a esta notificación se va ejecutar esta funcion, siempre retornado un error:
"Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value", claro esta porque no existe ningún scrollView para asignarle el contentInset solo en caso de que este presenta la vista "CardView".
Tendría que solucionar esto de alguna manera, sugiero agregar ese observer solo cuando este presente la vista CardView y removerlo cuando este se oculta, aquí hay un post sobre esto
https://stackoverflow.com/questions/5624975/removing-all-notification-observer-from-a-single-place. 
Si es posible hacerlo cuanto antes ya que no he podido compilar mi app con la version 2.0.7 ya que no hay manera de solucionarlo, debido a que todo esta dentro de un framework...
Saludos

**Comment by hugohernandez** [comment]
Hola @risalgue,

En la versión 2.0.7 se eliminó el uso completo de NotificationCenter.default.addObserver. Tendrás algún log que nos puedas compartir?.

Saludos.

**Comment by risalgue** [comment]
Aqui te envío un Crash Report que he generado hace unos instantes

[Towgee-2019-06-04-135818.crash.zip](https://github.com/open-pay/openpay-swift-ios/files/3253901/Towgee-2019-06-04-135818.crash.zip)

**Comment by hugohernandez** [comment]
Hola @risalgue,

Ya revise y tengo una duda, como implementó la función "func successToken(token: OPToken) {}".

Saludos.

**Comment by hugohernandez** [comment]
> Hola @risalgue,
> 
> Ya revise y tengo una duda, como implementó la función "func successToken(token: OPToken) {}".
> 
> Saludos.

Realizando pruebas pude replicar el error que comenta, pero este se da por la implementación propia que hicimos en nuestra App de Ejemplo, en específico es cuando tratamos de instanciar el ViewController donde mostramos los resultados.

Pregunta, usted hace algo similar ?
if let resultController = storyboard!.instantiateViewController(withIdentifier: "ResultController") as? ResultViewController {
.
.
}

Saludos.

**Comment by risalgue** [comment]
La implementación de openpay no le da problemas, lo que me da problemas y es el Crash es el terminar de seleccionar una dirección del GMSAutocompleteViewController de La SDK de Google maps. Pasa nada más que cuando tiene la librería de openpay agregada.

Enviado desde mi iPhone

**Comment by hugohernandez** [comment]
Tendrá algún otro log con más detalle del error.

Saludos.

**Comment by falguninayak** [comment]
ese todo lo que tengo del error, si es posible reprodúzcalo, aquí te envío un proyecto que cree de pruebas para que veas que pasa con el error, hasle un pod install para que descargues las librerías de google. comenta la linea 18 donde se inicializa la variable OpenPay y de esta manera no da error
[Proyect.zip](https://github.com/open-pay/openpay-swift-ios/files/3257835/Proyect.zip)

**Comment by risalgue** [comment]
ese todo lo que tengo del error, si es posible reprodúzcalo, aquí te envío un proyecto que cree de pruebas para que veas que pasa con el error, hasle un pod install para que descargues las librerías de google. comenta la linea 18 donde se inicializa la variable OpenPay y de esta manera no da error
[Proyect.zip](https://github.com/open-pay/openpay-swift-ios/files/3257844/Proyect.zip)
 (Prueba en el simulador, si quieres probar en un iPhone agrega el framework para iPhone)

**Comment by hugohernandez** [comment]
Hola @risalgue,

Gracias por la información, lo revisaré.

Saludos.

**Comment by hugohernandez** [comment]
Hola @risalgue,

Acabo de ejecutar tu ejemplo y efectivamente se crashea cuando realizas una búsqueda.

Ahora bien, tu ejemplo tiene la v2.0.4 de la librería de Openpay. Si actualizo la versión a la v2.0.7 funciona correctamente.

Saludos.

**Comment by risalgue** [comment]
Remplace la version por la 2.0.7 y funciono bien, también solo inicialize la variable nada mas que cuando la vaya usar...
