### ISSUE TITLE
Could not find module 'Openpay' for architecture 'arm64'; found: i386, x86_64 

### ISSUE THREAD

**Issue by alejandroban** [open-pay/openpay-swift-ios#35]
Could not find module 'Openpay' for architecture 'arm64'; found: i386, x86_64  
Tengo este error al generar el archive ya eh puesto el framework para os y me sigue ocasionando ese error

**Comment by memovillalobos** [comment]
Importa el archivo **Openpay.framework** desde la carpeta **iphonesimulator** en lugar de utilizar el archivo de la carpeta iphoneos

**Comment by SHARON-iOS** [comment]
I'm also stuck in this issue "Could not find module 'Openpay' for target 'arm64-apple-ios'; found: i386, x86_64". 
Do you have any solutions?

**Comment by alejandropablo9** [comment]
yes
delete completely the framework simulator from your project folder 
and copy the framework so

**Comment by genalex2** [comment]
Tengo el mismo problema, alguna solucion?
