### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by navalCodebrew** [open-pay/openpay-swift-ios#39]
I am using openpay framework  universal version (SDK V 2.0.2).
swift version 4.2
my app  goes crash when I uses this following method:

openpay.loadCardForm(in: self, successFunction: successCard, failureFunction: failCard, formTitle: "Openpay")

I am not getting any type of error in the Xcode console.
So Please check this issue and give me any solution regarding this issue ASAP.

**Comment by darkhorse-coder** [comment]
- ios 13.+
- swift compiler 5.3+
- real ios 13.6 device

when create new token by 

 ```
func initOpenpay() {
        m_openPay = Openpay(withMerchantId: OP_MARCHANT_ID, andApiKey: OP_PUBLIC_API_KEY, isProductionMode: false)
        m_openPay.loadCardForm(in: self, successFunction: successCard, failureFunction: failedCard, formTitle: "Openpay")
    }

    func successCard() {
        m_openPay.createTokenWithCard(address: nil, successFunction: successToken, failureFunction: failedToken)
    }
    
    func failedCard(err: NSError) {
        print(err.localizedDescription)
    }
    
    func successToken(token: OPToken) {
        print(token.id)
    }
    
    func failedToken(err: NSError) {
        print(err.localizedDescription)
    }
```

app crash.
![Screen Shot on 2020-08-21 at 21-44-25](https://user-images.githubusercontent.com/32187178/90948835-8ec62900-e3f7-11ea-9cd7-27304191066c.png)

Please check and help for this issue Openpay_v2.0.12.
