### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compile

### ISSUE THREAD

**Issue by Jtostado58** [open-pay/openpay-swift-ios#40]
Estoy teniendo este error: Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compile Con la nueva version de Xcode 11. ¿saben si van a sacar un SDK actualizado, o como puedo lograr que swift 5.1 lo lea?

**Comment by Alecattie** [comment]
El mismo problema estoy teniendo yo! alguien sabe cuando sacan uno actualizado?

**Comment by aniiskywalker** [comment]
El mismo problema, ¿alguna idea de cómo resolverlo o cuándo van a hacer el release que soporte xcode 11?

**Comment by Pankecho** [comment]
Hoy subieron al release una nueva versión.

**Comment by aniiskywalker** [comment]
Yo sigo viendo la 2.0.9 👎

**Comment by jonathanlopez** [comment]
Presento el mismo inconveniente luego de actualizar el xCode 11. Versión 2.0.9.
Alguna fecha pautada para la actualización?

**Comment by Jtostado58** [comment]
Una solución temporal que encontré es descargar Xcode 10 o alguno anterior al 11 y probar todo desde ahí hasta que salga la actualización

**Comment by Pankecho** [comment]
https://github.com/open-pay/openpay-swift-ios/releases 
Ahi ya aparece la version 2.0.10 compilada con Swift 5.1
Igual me dio mucha lata, queria migrar una aplicación y no podía por Open Pay
Ahora ya todo bien :)

**Comment by darkhorse-coder** [comment]
I have tried for v2.0.10 on xcode 11.2
But still I have got error

`Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Volumes/Work/IOS_Mac/10_OrderingApp/Project/ordering-ios-app/Ordering App/Openpay.framework/Modules/Openpay.swiftmodule/arm64-apple-ios.swiftmodule`

Any solution?

**Comment by darkhorse-coder** [comment]
> https://github.com/open-pay/openpay-swift-ios/releases
> Ahi ya aparece la version 2.0.10 compilada con Swift 5.1
> Igual me dio mucha lata, queria migrar una aplicación y no podía por Open Pay
> Ahora ya todo bien :)

Currently, xcode v11.0 and Openpay sdk 2.0.10 is compatible.
For Ios 13.0, anyone can consider this. Thanks.
