### ISSUE TITLE
Get OPToken by creating the OPCard object manually, skipping the form

### ISSUE THREAD

**Issue by gonzaaasanchez** [open-pay/openpay-swift-ios#44]
The Objective-C SDK allows us to create a token with an OPCard object as a parameter, whereas in the Swift SDK the same function receive an OPAddress object and cannot be called without displaying the form before.

Is there any chance to reach the same flow as the Objective-C SDK, by creating the token directly with an OPCard object and skipping the form?
In the project in which I'm trying to integrate the SDK, I don't want the user to re-enter the card data, that's why displaying the form is something I would prefer to avoid.

Thanks in advance!

**Comment by iamenrique** [comment]
Agree with @gonzaaasanchez. I'm wondering what you did. The form provided by the SDK has a poor UI/look-and-feel. Makes no sense that the Obj-C SDK handles things different.

**Comment by iamenrique** [comment]
And apparently OpenPay is not concerned about it.
