### ISSUE TITLE
How to customize form UI or avoid to use embedded card form?

### ISSUE THREAD

**Issue by erikjhordan-rey** [open-pay/openpay-swift-ios#46]
We want to avoid to use the embedded card form, so it's not needed to force clients to use it. You should provide a more flexible API to create a token without form UI to those architectures where handle custom forms.

You could provide a way to send a card model and return the `OpToken` without to force to use the UI as same as objective c sdk does.

**Comment by iamenrique** [comment]
Hi @erikjhordan-rey 
Were you able to avoid using the provided form or what's the workaround you came with? I'm having the same problem. 

Thanks in advanced

**Comment by ijpe** [comment]
Same problem, my recommendation is that you need to send _card information_ and a _device_session_id_ (generated on app with the `SDK`) to backend, and create a card using the `OpenPay API`

**Comment by erikjhordan-rey** [comment]
@enriqued93 In our case, we adopt open pay objective C version it's more flexible API, but it's not maintained at the end we don't use it anymore, we change the provider.

**Comment by iamenriqueiks** [comment]
@ijpe Yes, I thought in doing that however at the end we decided to do not proceed like that due to PCI compliance. Sensitive data (i.e. card information) must not be sent to/through our servers but directly by the providers' means.

**Comment by iamenriqueiks** [comment]
@erikjhordan-rey Thanks for the update. We also had to change the provider because we found other issues as well among this one. :/
