### ISSUE TITLE
Dispositivo inválido

### ISSUE THREAD

**Issue by marco-evc** [open-pay/openpay-swift-ios#47]
Hola,
Tengo un problema con el device_session_id y las transacciones. El device_session_id lo estoy generando con la última versión publicada para swift, tal y como lo mencionan en la documentación, de la siguiente manera:

``` 
public func createSession() {
    let openpay: Openpay = Openpay(withMerchantId: MERCHANT_ID, andApiKey: API_KEY, isProductionMode: false, isDebug: false)
    openpay.createDeviceSessionId(successFunction: successSessionID(sessionID:), failureFunction: failSessionID(error:))
  }

  func successSessionID(sessionID: String) {
    print("SessionID: \(sessionID)")
  }

  func failSessionID(error: NSError) {
    print("\(error.code) - \(error.localizedDescription)")
  } 
```
Esto genera un id como lo siguiente:
**020ED45F2F4CS60D86FDD068755FC06A**

Sin embargo, al consumir su API, se hace la transacción de manera exitosa, pero en el dashboard aparece como **Dispositivo inválido**,  adjunto evidencia

<img width="1201" alt="Screen Shot 2020-01-21 at 22 55 29" src="https://user-images.githubusercontent.com/28282690/72868408-8e21b480-3ca7-11ea-81bd-38a1847ea1dc.png">
<img width="414" alt="Screen Shot 2020-01-21 at 22 54 39" src="https://user-images.githubusercontent.com/28282690/72868421-97ab1c80-3ca7-11ea-9650-a4575c0fbeef.png">
<img width="1216" alt="Screen Shot 2020-01-21 at 22 54 29" src="https://user-images.githubusercontent.com/28282690/72868434-9bd73a00-3ca7-11ea-8192-46e249471f84.png">

Como nota adicional, ya hice pruebas generando el device_session_id con la librería de Objective-C y con la librería de Swift, en ambos casos con el mismo resultado.

**Comment by gumoz** [comment]
Tengo exactamente el mismo problema.
<img width="500" alt="Screen Shot 2020-07-01 at 17 58 04" src="https://user-images.githubusercontent.com/48006/86298876-763e4d00-bbc4-11ea-87f1-55275c6a1ed1.png">

**Comment by hfernandez801** [comment]
Algun nuevo estatus de esta situacion y como afecta al proceso, he notado el mismo comportamiento al menos en sandbox.

**Comment by menidh69** [comment]
A mi me sucede lo mismo, @carloshe-perez alguna clase de respuesta o soporte para este problema?

**Comment by carloshe-perez** [comment]
![image](https://user-images.githubusercontent.com/77075921/114105693-d4563a00-9892-11eb-8830-2c8c7e38b57d.png)

Hola, acabamos de hacer una prueba con la nueva version y en sandbox se registra bien el pago. Puedes utilizar la nueva version de la libreria?

![image](https://user-images.githubusercontent.com/77075921/114105871-3b73ee80-9893-11eb-8131-30b4f3698b4b.png)

![image](https://user-images.githubusercontent.com/77075921/114105887-43cc2980-9893-11eb-942d-58d875dac584.png)

![image](https://user-images.githubusercontent.com/77075921/114106041-93125a00-9893-11eb-9e73-df23c2283197.png)

**Comment by dcabrera1499** [comment]
Hola que tal, tengo este problema en Android Java, puedo hacer los cargos sin problema pero me dice que el dispositivo es invalido. Por favor si alguien conoce la solución a este caso les agradecería que la compartan para aclarar dudas. Gracias. 
👍

**Comment by carloshe-perez** [comment]
Nos podrías dar más datos de tu implementación? Y con los siguientes datos:
1.- Version del SDK
2.- Si nos puedes ayudar con los accesos de tu comercio para validar como están llegando las peticiones…. despues podrías restablecerlas.

**Comment by jesusedhas** [comment]
Hola, en Android funciona correctamente pero tengo este problema en iOS, podría ayudarme?

**Comment by carloshe-perez** [comment]
Podrias darme mas detalles del error? En iOS la generacion de token es asincrona y se debe de generar un token para cada transaccion. Si nos das mas detalles de tu implemntacion o abres un nuevo caso podriamos ayudarte.

**Comment by jesusedhas** [comment]
gracias, ya abrí un nuevo issue
