### ISSUE TITLE
UIWebView deprecated

### ISSUE THREAD

**Issue by ajuarezjc** [open-pay/openpay-swift-ios#48]
I was trying to upload my app to the AppStore but received the next mail:

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). | ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
-- | --
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

The lastest version of this SDK is still using UiWebView, which prevents us from uploading new binaries.

**Comment by iamenrique** [comment]
Hi, 
Is there any update on this? I'm about to integrate the SDK and I don't want to have the same problem. If that's the case, what would be a PCI-compliant workaround?
