### ISSUE TITLE
Soporte para Swift 5.3

### ISSUE THREAD

**Issue by em4n0101** [open-pay/openpay-swift-ios#49]
¿Podrían actualizar su SDK para soportar Xcode 12? Al intentar compilar marca el siguiente error:

**Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler**

Gracias

**Comment by victorhugo** [comment]
Yo probé una opción que vi en internet
Setting project.pbxproj file as:

BUILD_LIBRARY_FOR_DISTRIBUTION = YES;

Pero NO funciona tampoco, necesitamos que lo vuelvan a compilar con la versión más reciente o no se puede enviar update con soporte para iOS 14.

**Comment by em4n0101** [comment]
> Yo probé una opción que vi en internet
> Setting project.pbxproj file as:
> 
> BUILD_LIBRARY_FOR_DISTRIBUTION = YES;
> 
> Pero NO funciona tampoco, necesitamos que lo vuelvan a compilar con la versión más reciente o no se puede enviar update con soporte para iOS 14.

También probé esa opción y tampoco funciono, tuve que quitar temporalmente el SDK para poder compilar mi proyecto
