### ISSUE TITLE
El sdk no tiene soporte para iOS 14 no compila y no puede enviar mi app a AppStore HELP!!

### ISSUE THREAD

**Issue by GUSTAVOYOAB** [open-pay/openpay-swift-ios#50]

**Comment by ajuarezjc** [comment]
A mi igual me pasa y no sé cuando actualizaran su SDK.

Lo que hice fue bajar Xcode 11.7 y seguir ese proyecto usando esa versión.
https://developer.apple.com/download/more/?q=xcode

**Comment by GUSTAVOYOAB** [comment]
Gracias , ya hicieron la actualización
https://github.com/open-pay/openpay-swift-ios/blob/master/README.md
