### ISSUE TITLE
Modulo para dispositivos físicos y simuladores

### ISSUE THREAD

**Issue by Jairolaya12x** [open-pay/openpay-swift-ios#58]
Hola

Existe la posibilidad de que hagan una compilación del modulo tanto para iOS como para simuladores en el mismo sin que queden separados?

Estoy desarrollando un plugin para usarlo dentro de flutter pero al estar separados complica el trabajo.

Gracias quedo atento.

**Comment by Jairolaya12x** [comment]
Porque se cerro el issue? 🥲

**Comment by carloshe-perez** [comment]
> Porque se cerro el issue? 🥲

La ultima liberación te es compatible para dispositivos físicos como simuladores.
