### ISSUE TITLE
Problems with iOS 11

### ISSUE THREAD

**Issue by astrocumbia** [open-pay/openpay-swift-ios#6]
The buttons for "Cancel" and "Continue" in the form don't work in devices with iOS 11. I test it in devices with iOS 10.3.3 and works normally.

**Comment by gorrotowi** [comment]
@igrijalva Hay solución próxima a esto? Muchos de nuestros clientes nos están reportando problemas en sus iPhones y estamos perdiendo mucho dinero ya que no hay forma de que se puedan agregar las tarjetas.

**Comment by igrijalva** [comment]
Estamos trabajando para solucionarlo, los mantendremos al tanto y en cuanto esté lista la actualización les informamos.

**Comment by igrijalva** [comment]
Gracias a Irvin Castellanos (@positr0nix) por la contribución.
