### ISSUE TITLE
Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4

### ISSUE THREAD

**Issue by ijpe** [open-pay/openpay-swift-ios#63]
Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4

**Comment by victorhugo** [comment]
Siempre van Super atrasados con updates de versión, además de que no lo compilan con Module Stability.

**Comment by carloshe-perez** [comment]
Hola! Subimos un cambio para usar XCFRAMEWORK que es más universal. Y el proyecto demo lo tiene configurado. 

![image](https://user-images.githubusercontent.com/77075921/120700391-37211780-c477-11eb-8d47-04afaaae0956.png)

Aqui la muestra de que se ejecuta con version 5.4.
