### ISSUE TITLE
Problemas al intentar subir aplicación a App Store

### ISSUE THREAD

**Issue by gilrodar** [open-pay/openpay-swift-ios#68]
Después de integrar su librería e intentar mandar una nueva versión a App Store Connect me regresaron este mensaje.

One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

<img width="677" alt="Captura de Pantalla 2022-03-15 a la(s) 14 09 02" src="https://user-images.githubusercontent.com/13817108/158463027-514ad93d-2ffb-4d55-b1d3-04e1f18369a0.png">

**Comment by danielm2402** [comment]
Estoy teniendo el mismo problema al subir a App Store. Alguna solución?

**Comment by carloshe-perez** [comment]
Has intentado con el proyecto de prueba? De nuestro lado validamos subiendo un compilado de prueba sin ningun problema del lado de app store.
