### ISSUE TITLE
2022 Dispositivo inválido en iOS

### ISSUE THREAD

**Issue by jesusedhas** [open-pay/openpay-swift-ios#69]
Hola, estoy usando la última versión del framework para swift (3.2.0 - Mar 09,2022) pero el cargo sigue apareciendo como "Cargo inválido" en el dashboard
https://github.com/open-pay/openpay-swift-ios/releases

solicitud al api y respuesta
![1](https://user-images.githubusercontent.com/8844525/199873543-5df62d77-1fb8-4301-a666-a7fee7a0c0dd.png)

leyenda de "Dispositivo inválido" en Tarjetas > Pagos
![2](https://user-images.githubusercontent.com/8844525/199873604-cca26a36-2330-44e2-b87a-93951fb85a52.png)

**Comment by carloshe-perez** [comment]
puedes descargar el proyecto de prueba que esta en repositorio, configurar tus keys de integracion y decirnos si con este proyecto tus cargos aparecen como dispositivo invalido de favor.

**Comment by jesusedhas** [comment]
ya pude realizar la integración correctamente, gracias por la orientación
